# Generated by Django 4.0.4 on 2022-06-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_restaurant_category_restaurant_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='updated',
        ),
    ]
