# Generated by Django 4.0.4 on 2022-06-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0006_rename_created_restaurant_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=120),
        ),
    ]
