# Generated by Django 4.0.4 on 2022-06-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0009_restaurant_sname_alter_restaurant_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='sname',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='updated',
        ),
    ]
