# Generated by Django 4.1 on 2022-09-08 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0012_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='assets'),
            preserve_default=False,
        ),
    ]
